### ISSUE TITLE
no recipe

### ISSUE THREAD

**Issue by Trixz2018** [Aang23/RSInfiniteWireless#1]
no recipe? and the tooltip is the advanced tooltip

**Comment by Aang23** [comment]
Oh ! Sorry ! I'm fixing that right now !

**Comment by Aang23** [comment]
While curse review the file, you can find a fixed build there : http://www.altillimity.com/jenkins/job/RSInfiniteWireless/lastSuccessfulBuild/artifact/build/libs/rsinfinitewireless-1.2-5.jar

Edit : the file is on curseforge now.
