### ISSUE TITLE
Fix Crash on new version RS

### ISSUE THREAD

**Issue by ferreiraalex** [Aang23/RSInfiniteWireless#4]
can you fix crash on map start?
[crash-2021-07-02_08.57.56-server.txt](https://github.com/Aang23/RSInfiniteWireless/files/6752428/crash-2021-07-02_08.57.56-server.txt)
this version of refined new!!
https://github.com/tth05/morerefinedstorage

**Comment by ferreiraalex** [comment]
i think close coz author leave minecraft modding

**Comment by embeddedt** [comment]
https://github.com/embeddedt/RSInfiniteWireless/releases/tag/v1.2.0
